BEGIN;
insert into ore(scavo, data, ore, operatore) values
(11, '08/01/2020', 2, 3),
(11, '09/01/2020', 4, 3),
(11, '10/01/2020', 8, 3),
(11, '13/01/2020', 4, 3),
(11, '14/01/2020', 6, 3),
(11, '15/01/2020', 8, 3),
(11, '16/01/2020', 8, 3),
(11, '17/01/2020', 8, 3),
(11, '17/01/2020', 8, 1),
(11, '17/01/2020', 4, 2),
(11, '20/01/2020', 1, 3),
(11, '22/01/2020', 1, 3),
(11, '24/01/2020', 5, 4),
(11, '24/01/2020', 8, 2),
(11, '24/01/2020', 8, 3),
(11, '27/01/2020', 8, 3),
(11, '27/01/2020', 8, 2),
(11, '28/01/2020', 8, 3),
(11, '28/01/2020', 8, 2),
(11, '29/01/2020', 8, 2),
(11, '29/01/2020', 8, 1),
(11, '30/01/2020', 8, 1),
(11, '30/01/2020', 8, 4),
(11, '31/01/2020', 8, 2),
(11, '31/01/2020', 8, 1),
(11, '03/02/2020', 8, 2),
(11, '03/02/2020', 8, 4),
(11, '04/02/2020', 8, 2),
(11, '04/02/2020', 8, 4),
(11, '05/02/2020', 8, 3),
(11, '05/02/2020', 6, 4),
(11, '06/02/2020', 8, 3),
(11, '06/02/2020', 8, 1),
(11, '06/02/2020', 8, 2),
(11, '06/02/2020', 8, 4),
(11, '07/02/2020', 8, 1),
(11, '07/02/2020', 8, 2),
(11, '07/02/2020', 8, 4),
(11, '10/02/2020', 8, 2),
(11, '10/02/2020', 8, 4),
(11, '11/02/2020', 8, 3),
(11, '11/02/2020', 8, 1),
(11, '11/02/2020', 8, 4),
(11, '12/02/2020', 8, 2),
(11, '12/02/2020', 8, 4),
(11, '13/02/2020', 8, 4),
(11, '13/02/2020', 8, 2),
(11, '14/02/2020', 8, 4),
(11, '14/02/2020', 8, 2);

insert into diario(scavo, data, operatore, descrizione) values
  (11, '08/01/2020', 3, 'Sopralluogo con Dr. Marzoli'),
  (11, '09/01/2020', 3, 'rimozione controllata ultime murature da abbattere. luca lizzare due cisterne di gasolio sul fronte Est (da bonificare); burocrazia per avviamento cantiere (protocollo sicurezza con firme originali e marche da bollo)'),
  (11, '10/01/2020', 3, 'rimozione controllata di murature e macerie; assistenza al mezzo meccanico; assistenza alla bonifica delle 2 cisterne individuate sul fronte Est; prime operazioni di pulizia in due aree potenzialmente interessanti: zona con argilla scottata e carboni presso una grossa pietra a firma di parallelepipedo sotto l''attuale sezione Est, con rinvenimento di un frammento ceramico antico); area ad W di un muro in cemento (sez. 1), con fossa riempita da uno strato Franco (US 1), al cui interno è stato rinvenuto un frammento di laminetta in bronzo)'),
  (11, '13/01/2020', 3, 'in mattinata: controllo cantiere per riunione sicurezza; nel pomeriggio: riunione sicurezza'),
  (11, '14/01/2020', 3, 'definizione limiti cantiere con geometra; controllo al mezzo meccanico'),
  (11, '15/01/2020', 3, 'controllo al mezzo meccanico; aperta l''area del settore SW (a lato della piscina); rimosso primo livello composto da suolo moderno; evidenziato un livello composto da sassi e pietre di piccole dimensioni con una rara matrice franco-sabbioso di colore rosato; sotto si individua un paleosuolo antico, con sporadici resti ceramici e di conforto (reperti pre-protostoricu); il paleosuolo è fortemente disturbato da numerosi sottoservizi (tubature della piscina, cavo parafulmine, tubi impianto irriguo, tubi in plastica arancione, forse uno scarico); avvertita la soprintendenza si prosegue con la rimozione controllata del paleosuolo, ma circa a metà settore (all''altezza del lato SW della piscina) l''escavatore espone una serie di grosse pietre allineate, che vengono lasciate in situ per ulteriori verifiche; si procede con la rimozione del paleosuolo a S dell''allineamento di pietre, esponendo tutta l''area. a questo punto su decide di eseguire un sondaggio profondo presso l''angolo NW del primo lotto di scavo: sotto il paleosuolo si incontrano livelli geologici (pietre di medie e grandi dimensioni in una matrice Franco sabbiosa rosa chiaro), ma ci si ferma in attesa della quotatura del fondo dello scavo (il giorno successivo), per evitare di sottoscavare l''area; sulla parete W del sondaggio profondo si comincia a vedere un accumulo di pietre di difficile interpretazione, quasi privo di matrice; bloccato il sondaggio profondo si cerca di eseguire un secondo sondaggio nell''angolo SW del lotto di scavo. anche qui si raggiunge il livello geologico caratterizzato da pietre e sabbia rosa chiaro, ma procedendo verso E si deve bloccare lo scavo per il comparire di un livello carbonioso molto sottile; le ultime ore della giornata vengono impiegate nella pulizia del livello carbonioso e del presunto muro'),
  (11, '16/01/2020', 3, 'si continua la pulizia del presunto muro. si evidenziano grosse pietre allineate, e molte piccole pietre in una rara matrice molto simile a quella del paleosuolo individuato il giorno prima. si recuperano vari reperti di ceramica protostorica e concotto'),
  (11, '17/1/2020', 3, 'controllo all''escavatore durante l''apertura del primo lotto di scavo (area SW); pulizia delle prime evidenze riscontrate nell''area (possibile muro o resti di struttura composta da grosse pietre allineate e accumulo areale di piccole pietre, con molti reperti e area con strato carbonioso e muro a secco.'),
  (11, '20/01/2020', 3, 'sopralluogo per scavo con escavatore; giornata annullata per assenza non comunicata del mezzo'),
  (11, '22/01/2020', 3, 'sopralluogo per scavo con escavatore; giornata annullata per assenza non comunicata del mezzo'),
  (11, '24/01/2020', 4, 'Pulizia dell''area settentrionale dello scavo, in superfice dello strato nero, presenza di ceramica, metallo e pochi ossi.'),
  (11, '27/01/2020', 3, 'pulizia dell''evidenza 1 (individuata nell''area E, presso l''attuale sezione); l''evidenza 1 (piano di argilla scottata, con numerosi frammenti di conforto e rari frammenti ceramici) appare come il crollo di una struttura abitativa (fine bronzo / inizio ferro); il piano di argilla scottata é spesso Ca. 20 - 30 cm ed è probabilmente il risultato del crollo del convitto dei muri; lo strato copre un livello di incendio originatosi sul piano d''uso della struttura); l''evidenza 1 pare dunque essere in connessione all''evidenza 2 (struttura sotto US 1), da cui è separata da unuro in cemento dell''hotel Kuhn e dalla relativa fossa di fondazione; viene portato via anche un camion di macerie dell''hotel Kuhn. il terreno è ancora ghiacciato in profondità, nonostante la copertura con geotessto spesso (3 strati)'),
  (11, '28/01/2020', 3, 'pulizia evidenza 1; piove per metà mattinata e metà pomeriggio; l''acqua ammorbidisce la terra ghiacciata e si pulisce un po'' più velocemente; a fine giornata l''evidenza 1 è praticamente pulita. a S è intaccata da una struttura tarda (fossa biologica moderna?); l''escavatore stacca verso le dieci (rimozione parziale asfalto lotto 3) e non ritorna'),
  (11, '29/01/2020',2, 'pulizia evidenza 1. alle 9 ispezione della dott.ssa Marzoli con discussione sul deposito archeologico esposto e impostazione delle strategie lavorative dei prossimi giorni. nel pomeriggio si finisce la pulizia dell''evidenza 1 e si procede alla documentazione fotografica e topografica della sezione 1 (FTP 2) e del piano (FTP 3).'),
  (11, '30/01/2020', 1, 'Pulizia dell''area settentrionale dello scavo (area2). dopo l''accordo telefonico con dottoressa Marzoli, per ragioni di sicurezza, ci siamo decisi di non scavare La trincea lungo la sezione meridionale dello scavo, ma è stata messa in sicurezza da parte della ruspa. il mezzo meccanico poi si è spostato nel settore settentrionale dello scavo e ha iniziato con l''asporto della stratigrafia superficiale. in pomeriggio il ruspista si è spostato su un altro cantiere ed il mezzo era fermo. sono state coperte solo le zone che non verranno intercettate. dopo l''aumento delle temperature, sarà possibile continuare con lo scavo in quell''area e di documentare il profilo Sud di evidenza 2. dopo la fine della pulizia nell''area settentrionale dello scavo, abbiamo documentato con fotopiano 4 US 10,11, e 13. abbiamo proseguito con la pulizia della sezione orientale, che è stata documentata con fotopiano 5. la sezione è stata pulito a scaline, per mantenere le prescrizioni della sicurezza del lavoro. in questo modo è stato possibile di mettere in evidenza molto chiara il piano di calpestìo formato da us10 e la stratigrafia sottostante. intanto sono state date lei us 14,15, 16 per gli strati coperti da us10. si continua a trovare ceramica dell''età del bronzo in superficie us10.'),
  (11, '31/01/2020', 2, 'controllo escavatore nella porzione mediana dello scavo attestandosi sul livello Franco argilloso grigiastro con frammenti di ceramica protostorica.(US10) Rimozione di un livello compatto con frammenti di laterizi e malta. alle 9 visita della dott.ssa Marzoli. nel pomeriggio pulizia a trowel della sezione 3 e di una porzione della nuova area liberata, vicino ad un allineamento di pietroni'),
  (11, '03/02/2020', 2, 'continua la pulizia del muro di terrazzamento Ok osservato nel settore Ovest dello scavo nella zona centrale. il muro sembra collegato alle stratigrafie antiche che portano in superficie materiale protostorico. verso nord-est sembra interrotto da una canaletta riempita da pietre e frammenti di Malta oltre a Coppi moderni. procedendo la pulizia verso nord è stato ripulito il la seconda struttura muraria coperta da un piccolo butto di pietre di piccole dimensioni. anche in questo caso la struttura sembra associata a strati con materiale protostorico. la ruspa asportato una piccola porzione di terreno nell''angolo nord-est tenendosi alta rispetto ai livelli archeologici. la polizia ha di fatto eliminato tutti i livelli recenti che sono caratterizzati dalla presenza di piccoli frammenti di Malta alcuni pezzi di Coppi e di laterizi di epoca moderna. questi materiali moderni aumentano di dimensioni a ovest delle strutture di terrazzamento in quanto probabilmente sono stati gettati con lo scopo di innalzare il terreno e livellarlo.'),
  (11, '04/02/2020', 2, 'durante la mattina l''arrivo dei camion ha permesso di liberare l''area dall''accumulo di terra dei giorni precedenti. in pomeriggio è stato continuato il controllo archeologico durante i lavori di scavo nell''area nord-est. a fine giornata ci si è attestati circa 40 cm sopra le stratificazioni archeologiche. al centro dell''area è stato individuato il saggio precedentemente scavato dalla ditta archeologica Rizzi. è emerso un allineamento di pietroni che potrebbe essere interpretato come muro di terrazzamento individuato anche durante i saggi dell''anno 2019. durante la mattina è stata effettuata la pulizia nell''area tra evidenza 3 ed evidenza 4. sono stati messi in luce un livello di terreno nerastro con carboni pianeggiante, che sembra di coprire lo sterile composto da sabbie e ghiaie di colore rosso. lo strato nero viene coperto da uno strato limo argilloso di colore grigio contenente materiale protostorico, che invece era coperto da strati di materiale moderno, tra cui frammenti di coppi e malta. come sembra attualmente, evidenza 3 sta coprendo lo strato nerastro, e viene coperto dallo strato grigio. evidenza 3 è composta da grossi pietroni allineati in senso nord-sud e piccole pietre posizionate con ordine tra di loro. in pomeriggio ci siamo concentrati all''evidenza 4 x individuare l''andamento delle pietre allineate verso est. il muro con andamento nord-sud sembrava di piegare a 90 gradi verso est. in questa direzione la struttura sembra compromessa da disturbi moderni e fino alla conclusione della giornata non è stato possibile definire l''andamento della struttura.'),
  (11, '05/02/2020', 3, 'il mezzo meccanico continua lo scavo delle stratigrafie superficiali lungo la strada statale. i camion asportano il materiale. la mattina incontro con la dottoressa Marzoli. abbiamo visto la situazione delle evidenze 3 e 4. ci siamo accordati di poter rimuovere le strutture tra le evidenze 3 e 4 una volta documentata la situazione. abbiamo concordato lo scavo di una trincea su tutta l''area di cantiere in direzione est-ovest, fino alla quota di scavo, per verificare la stratigrafia. la posizione esatta è ancora da concordare con le esigenze dell escavatorista. in seguito sono stati assegnati tutti i numeri alle unità stratigrafiche delle evidenze due tre e quattro, ed inoltre alla sezione 3. con fotopiano 7 è stata documentata evidenza numero 3, ed inoltre tutti i reperti registrati presenti in superficie. alla fine della mattinata abbiamo iniziato con lo scavo di u.s. 28. in pomeriggio si continua con l''assistenza al mezzo meccanico.'),
  (11, '06/02/2020', 3, 'durante tutta la giornata si è effettuata la rimozione dello strato geologico, probabilmente uno smottamento di versante, che copre l''evidenza 5. si tratta di un livello composto principalmente da piccole pietrine di litotipo locale inseriti in una matrice sabbiosa. lo strato geologico è infilato tra le pietre dell''evidenza 5 fino a livello del paleosuolo. l''evidenza 5 è composta da grossi pietrone disposte su due file regolari e parallele. Alcuni elementi sono spostati a valle rispetto all''allineamento originario probabilmente a causa dello smottamento geologico. Tra la pietra spostata e il paleosuolo si è infilato nella fessura lo strato geologico. Contemporaneamente sono state compilate le schede di unità stratigrafica relative all''evidenza 2 e 3. Con il mezzo meccanico se continuato a esporre la sezione settentrionale delli scasso dell''hotel, liberando dalle macerie del perimetrale.'),
  (11, '07/02/2020', 1, 'durante la mattina si continua la rimozione del livello presunto geologico tra le pietre dell''evidenza 5. ci si testa sopra un livello limo sabbioso su cui sembrano appoggiare le pietre dell''evidenza 5. Lo scavo ha permesso di individuare almeno tre allineamenti paralleli ed un quarto leggermente inclinato rispetto ai precedenti. Alcune pietre sembrano mosse da un evento naturale, uno smottamento, e la loro posizione originale è indicata dal salto di quota visibile nel livello limo sabbioso. Durante il pomeriggio la ruspa continua l''apertura sul limite est dello scavo esponendo alcuni massi in allineamento con i precedenti. Sempre nel pomeriggio è iniziata la pulizia di fino. La fascia centrale di evidenza 5 sulla quale si basano i pietroni, è formata da uno strato limo sabbioso molto fino e orizzontale. Sembra di formare una specie di terrapieno, che si distingue soprattutto col fatto che non sia solo inclinato sul versante a valle ma anche su quello a monte. Come ipotesi di lavoro stiamo valutando la possibilità che si potrebbe trattare di un pezzo di strada preistorica. Nonostante il fatto che vicino all''area di intervento dovrebbe passare anche una strada di epoca romana, la forma e la struttura di evidenza 5 non sembra di assomigliare una strada di quell''epoca.'),
  (11, '10/02/2020', 2, 'Oggi abbiamo esposto evidenza 5 fino al limite di scavo orientale. la struttura lineare sembra di continuare in direzione sud-est. nell''area esposta era possibile osservare vari disturbi di epoca moderna, per esempio tubature di cemento, ceramica recente virgola vetro e plastica. mentre la struttura lineare e lo strato di ghiaia che lo copre sono privi di materiale moderno. finita la rimozione dello strato di ghiaia abbiamo continuato con la pulizia di fino. nelle zone pulite è possibile osservare che alcune pietre sono immerse nello strato Limo sabbioso di colore grigio  che forma la base del terrapieno, mentre altre si appoggiano su pochi centimetri della stessa ghiaia che copriva tutta l''evidenza 5. potrebbero essere state mosse dalla ghiaia da monte verso valle. lungo gran parte della struttura lineare evidenza 5 sembra essere ancora possibile osservare le impronte della posizione originale dei pietroni. a termine dei lavori abbiamo contattato la dottoressa Marzoli per informarla sulla situazione. Ci siamo messi daccordo di fare un sopralluogo martedì mattina.'),
  (11, '11/02/2020', 3, 'si conclude lo scavo di us 27 che equivale us13 (evidenza 2). Non risulta ulteriormente strutturata, e si appoggia sul piano di frequentazione antico. (Us10) Tra i reperti troviamo resti di ceramica, di laterizi, e pochi elementi in ferro e frammenti di osso. è stata terminata la pulizia dell''evidenza n 5 e si è proceduto con la documentazione. in mattinata C''è stato il sopralluogo del funzionario della soprintendenza. È stato concordato di procedere alla rimozione con mezzo meccanico dell''evidenza 5. è stato concordato anche di aprire una trincea lungo il lato Ovest dell''area di scavo'),
  (11, '12/02/2020', 2, 'dopo aver campionato us10 sia come sedimento che dei resti di carbone, abbiamo recuperato reperti ceramici in superficie è fatto rimuovere le pietre di evidenza 5 dal mezzo meccanico. in seguito la superficie esposta è stata controllata con il metalldetector. la superficie esposta non porta segni di ulteriori strutture sottostanti, ne buche o concentrazioni di carboni. il controllo con il metalldetektsts dando risultato nell''area meridionale di evidenza 2. una prima indagine ha portato in metallicaluce resti di scorie metalliche. la situazione non è ancora stata approfondita. in pomeriggio il mezzo meccanico inizia con lo scavo nell''area settentrionale di poggetto. la situazione risulta parzialmente compromessa da tubi moderni, anche sul piano nuovamente esposto non si notano segni di stratigrafie archeologiche. continua lo scavo di evidenza 3, us 17. come già ipotizzato il precedente, us17 si appoggia alla struttura us 20 e 21. lo strato carbonioso us18 si estende su tutta l''area sottostante. il ritrovamenti si limitano a pochi resti ceramici e ossa. la giornata si conclude con la documentazione ed il campionamento di us 41. (Ftp9)'),
  (11, '13/02/2020', 4, 'durante mattina si scava e si campiona us 41 documentata il giorno precedente. in seguito viene ripresa la pulizia dello strato nero carbonioso (US 18) sul limite occidentale dell''area di scavo in prossimità dell''evidenza 3. lo strato nero si interrompe bruscamente verso sud all''altezza dell''evidenza 4 dov''è è rotto da un taglio di erosione (US 43). dentro il taglio si osservano pietre e pietroni di porfido disposti caoticamente che sono probabilmente il risultato di una frana e smottamento. le pietre quindi dell''evidenza 4 non sono da sociare ad un intervento antropico ma ad un evento naturale. nel pomeriggio si asporta a mezzo meccanico in maniera assistita il grosso strato grigio (us 17) che copre sul limite orientale lo strato nero. questo scavo ha permesso di mettere in luce maggiormente il taglio di erosione US 43. si procede alla pulizia di fino delle stratificazioni esposte ed in serata si procede la documentazione archeologica e tridimensionale.');

  insert into fotopiano(scavo, num_fotopiano, us, data, note, autore, elaborato) values
    (11, 1, 'inizio scavo', '24/1/2020', 'sezione 1 (prima evidenza rinvenuta: probabili resti diuro a secco, con drenaggio e terra scusa)', 3, 't'),
    (11, 2, 'sez 1', '29/1/2020', 'rifatta sezione 1', 3, 't'),
    (11, 3, 'da 5 a 8', '29/1/2020','',4, 't'),
    (11, 4, '10, 11, 13', '30/1/2020', 'Area settentrionale dello scavo: evidenza 2, solo 3d', 4 ,'f'),
    (11, 5, '10, 14, 15, 16', '30/1/2020', 'Area 3, sezione est (sezione2), solo3d', 2, 'f'),
    (11, 6, 'area 3 sez. Nord', '31/1/2020', 'area 3 sez nord', 3, 'f'),
    (11, 7, 'evidenza 3', '05/02/2020', 'evidenza3', 3, 'f'),
    (11, 8, '10, 33 a 39.', '2020-02-11', 'evidenza 5', 2, 'f'),
    (11, 9, '41', '2020-02-02', '', 2, 'f'),
    (11, 10, '43', '2020-02-13', 'solo 3d', 2, 'f'),
    (11, 11, '17,19,42,-43', '2020-2-14', 'evidenza 3', 4, 'f'),
    (11, 12, 'sez 19, 17', '14/02/2020', 'sez', 4, 'f'),
    (11, 13, 'US 21 e 20', '14/02/2020', 'piano', 4, 'f');

  insert into reperto(scavo, us, reperto, materiale, tipologia, note, data, operatore) values
    (11,13, 1, 1, 1, 'orlo', '2020-01-24', 2),
    (11,7, 2, 2, 11, 'lama coltello ferro', '2020-01-24', 3),
    (11,5, 3, 1, 5, 'fondo ceramica', '2020-01-24', 2),
    (11,8, 4, 1, 5, 'fondo ceramica', '2020-01-24', 2),
    (11,10, 5, 3, 12, 'spillone bronzo', '2020-01-24', 3),
    (11,11, 6, 13, 13, 'ciottolo coppellato', '2020-01-24', 4),
    (11,17, 7, 3, 14, 'frammenti di fibula decorata', '2020-02-05', 1),
    (11,17, 8, 3, 15, 'medaglione rotondo', '2020-02-05', 2),
    (11,22, 9, 3, 16, 'elemento piatto con apicagnolo', '2020-02-05', 3),
    (11,18, 10, 3, 12, 'frammento di spillone', '2020-02-05', 4),
    (11,24, 11, 1, 6, 'attacco d''ansa', '2020-02-05', 3),
    (11,24, 12, 1, 1, 'orlo', '2020-02-05', 3),
    (11,24, 13, 1, 1, 'orlo', '2020-02-05', 3),
    (11,24, 14, 1, 1, 'orlo', '2020-02-05', 2),
    (11,10, 15, 1, 1, 'orlo', '2020-02-05', 2),
    (11,10, 16, 1, 1, 'orlo', '2020-02-05', 3),
    (11,10, 17, 1, 1, 'orlo', '2020-02-05', 4),
    (11,10, 18, 2, 17, 'chiodo', '2020-02-05', 3),
    (11,10, 19, 3, 16, 'elemento in bronzo', '2020-02-05', 2),
    (11,29, 20, 1, 1, 'orlo', '2020-02-05', 3),
    (11,28, 21, 1, 1, 'orlo', '2020-02-05', 1),
    (11,13, 22, 1, 1, 'orlo', '2020-02-11', 1),
    (11,13, 23, 1, 1, 'orlo', '2020-02-11', 2),
    (11,13, 24, 1, 1, 'orlo', '2020-02-11', 3),
    (11,13, 25, 1, 1, 'orlo', '2020-02-11', 4),
    (11,13, 26, 1, 1, 'orlo', '2020-02-11', 3),
    (11,13, 27, 1, 1, 'orlo', '2020-02-11', 2),
    (11,13, 28, 1, 1, 'orlo', '2020-02-11', 2),
    (11,13, 29, 1, 1, 'orlo', '2020-02-11', 3),
    (11,13, 30, 1, 1, 'orlo', '2020-02-11', 2),
    (11,13, 31, 1, 1, 'orlo', '2020-02-11', 3),
    (11,13, 32, 1, 1, 'orlo', '2020-02-11', 3),
    (11,13, 33, 1, 6, 'attacco d''ansa', '2020-02-11', 2),
    (11,13, 34, 1, 6, 'attacco d''ansa', '2020-02-11', 2),
    (11,13, 35, 1, 5, 'piede', '2020-02-11', 2),
    (11,13, 36, 1, 1, 'orlo', '2020-02-11', 2),
    (11,13, 37, 2, 17, 'chiodo', '2020-02-11', 4),
    (11,13, 38, 2, 17, 'testa di chiodo', '2020-02-11', 4),
    (11,32, 39, 1, 1, 'orlo', '2020-02-11', 4),
    (11,32, 40, 1, 1, 'orlo', '2020-02-11', 2),
    (11,32, 41, 1, 1, 'piede', '2020-02-11', 2),
    (11,32, 42, 1, 1, 'piede', '2020-02-11', 1),
    (11,32, 43, 2, 16, 'elemento di ferro', '2020-02-11', 1),
    (11,32, 44, 2, 17, 'chiodo', '2020-02-11', 2),
    (11,32, 45, 2, 17, 'chiodo', '2020-02-11', 2),
    (11,10, 46, 3, 16, 'elemento piegato', '2020-02-12', 3),
    (11,41, 47, 3, 16, 'elemento frammentato', '2020-02-12', 4),
    (11,10, 48, 3, 18, 'ago in bronzo', '2020-02-12', 3),
    (11,10, 49, 1, 5, 'fondo', '2020-02-12', 3);

    insert into us(scavo,us,tipo,definizione,compilazione,compilatore,chiusa) values
    (11, 1, 1, 'livello Franco, di colore bruno scuro, individuato nella sezione 1','16/02/2020',2,'t'),
    (11, 2, 2, 'taglio verticale che intacca US 1 (eseguito per la messa in opera di USM 4)','16/02/2020',2,'t'),
    (11, 3, 2, 'fossa riempita da US 1','16/02/2020',2,'f'),
    (11, 4, 1, 'muro moderno in cemento e pietre messo in opera contro-terra','16/02/2020',2,'t'),
    (11, 5, 1, 'livello argilloso beige sotto US 6.','16/02/2020',2,'t'),
    (11, 6, 1, 'livello argilloso rosso con convitti. crollo delle pareti dell''evidenza 1','16/02/2020', 2, 't'),
    (11, 7, 1, 'accumulo di pietre ciottoli e massi forse per il degrado dei perimetrali dell''evidenza 1', '16/02/2020', 2, 'f'),
    (11, 8, 1, 'livello Franco argilloso marrone scuro che copre US 7 e si sviluppa a sud di questa','16/02/2020',2,'t'),
    (11, 9, 1, 'struttura muraria a secco rimasta ormai per un unico pietrone. perimetrale nord dell''evidenza 1', '16/02/2020', 2, 'f'),
    (11, 10, 1, 'strato localmente annerito (paleosuolo), altrimenti tendente al grigio, con pochi reperti. spessore medio 10 cm. matrice francovargillosa. inclinazione da Monte a valle.', '16/02/2020', 2, 'f'),
    (11, 11, 1, 'riempimento con cemento malta nylon', '16/02/2020', 2, 't'),
    (11, 12, 2, 'taglio moderno riempito da US 11', '16/02/2020', 2, 'f'),
    (11, 13, 1, 'struttura in pietra, orientata in direzione nord-sud. si estende per una lunghezza di circa 8 metri. apparentemente copre us10 da verificare. si chiama evidenza due.', '16/02/2020', 2, 'f'),
    (11, 14, 1, 'strato limo argilloso sotto us10', '16/02/2020', 2,'f'),
    (11, 15, 1, 'strato limo argilloso con abbondante presenza di pietre di medie dimensioni sotto us14', '16/02/2020', 2, 'f'),
    (11, 16, 1, 'strato rossiccio con presenza di clasti di piccole medie dimensioni sotto us 15', '16/02/2020', 2, 'f'),
    (11, 17, 1, 'strato franco-limoso, grigio, compatto, con andamento planare, spesso Ca. 5 cm, rinvenuto nell''evidenza 3 (a copertura di US 18)', '16/02/2020', 2, 'f'),
    (11, 18, 1, 'sottile livello carbonioso, nero, friabile, individuato nell''evidenza 3 (sotto US 17, sopra US 19)', '16/02/2020', 2, 'f'),
    (11, 19,1, 'strato franco-sabbioso, rossiccio, dalla consistenza sciolta, con abbondante scheletro in pietre dagli angoli arrotondati, individuato nell''evidenza 3, sotto US 18). probabilmente smottamento sterile', '16/02/2020', 2, 'f'),
    (11, 20, 1, 'accumulo di grosse pietre allineate a spigoli vivi, individuate nell''evidenza 3','16/02/2020',2, 'f'),
    (11, 21, 1, 'accumulo di piccole pietre a riempimento delle intercapedini di US 20 e a parziale copertura della stessa US (nonché di US 17), individuato nell''evidenza 3','16/02/2020',2, 'f'),
    (11, 22, 1, 'strato limo-sabbioso di colore rossiccio, consistenza friabile e con scarso scheletro in piccoli sassi, individuato nell''evidenza 4 (tagliato da -23, copre 17, 25 e 26)','16/02/2020',2, 'f'),
    (11, 23, 2, 'taglio a pianta irregolare e fondo concavo, che intacca US 22, 17 e 26), riempito da US 24','16/02/2020',2, 'f'),
    (11, 24, 1, 'riempimento franco-sabbioso di US -23, di colore rossiccio, consistenza sciolta e scheletro in sassi, piccole pietre, ghiaia e reperti moderni (laterizi, cemento, ecc...)','16/02/2020',2, 'f'),
    (11, 25, 1, 'allineamento (e-w) di grosse pietre a spigoli vivi','16/02/2020', 2, 'f'),
    (11, 26, 1, 'accumulo di piccole pietre a spigoli arrotondati, nelle intercapedini di US 25 e a parziale copertura della stessa','16/02/2020',2, 'f'),
    (11, 27, 1, 'allineamento (e-w) di grosse pietre a spigoli vivi, nell''evidenza 2','16/02/2020',2, 'f'),
    (11, 28, 1, 'piccole pietre a spigoli arrotondati, tra le intercapedini di US 27 e attorno alla stessa (a copertura di US 10)','16/02/2020',2, 'f'),
    (11, 29, 1, 'sezione 3: accumulo di pietre di varie dimensioni (tendenzialmente piccole a monte e più grandi a valle), con scarsa matrice Franco sabbiosa grigio scuro. sono presenti rari ossi o reperti antropic i) (ceramica). copre US 30 e riempie US -31. è coperto da US 10 (potrebbe trattarsi di materiale legato ad un episodio di erosione e deposizione di un ruscello montano, ma anche di una mossa antica che è andata a riempire una vecchia incisione di un ruscello (sopra la quale si è poi formato diacronicamente il paleosuolo US 10)', '16/02/2020', 2, 'f'),
    (11, 30, 1, 'sezione 3: strato sabbioso Franco grigio-marrone, friabile, sotto US 29. potrebbe essere un primo paleosuolo formatosi su detriti deposti fa un ruscello durante un episodio di esondazione.', '16/02/2020', 2, 'f'),
    (11,31,2, 'taglio a V di tipo erosivo da ruscello montano (riempito da US 30 e 29). taglia US 19', '16/02/2020', 2, 'f'),
    (11,32,1, 'strato di ghiaia alluvionale che oblitera evidenza 5.', '16/02/2020', 2, 'f'),
    (11,33,2, 'negativa in US 10, di forma rettangolare allungata (SW-NE). tra le negative dell''evdenza 5 è quella più a monte (N)', '16/02/2020', 2, 'f'),
    (11,34,2,'negativa in US 10, di forma rettangolare allungata (SW-NE). è a S di US -33','16/02/2020', 2, 'f'),
    (11,35,2,'negativa in US 10, di forma rettangolare allungata (SW-NE). è a S di US -34','16/02/2020', 2, 'f'),
    (11,36,2,'negativa in US 10, di forma rettangolare allungata (SW-NE). è a S di US -35','16/02/2020', 2, 'f'),
    (11,37,2,'negativa in US 10, di forma rettangolare allungata (SW-NE). è a S di US -36','16/02/2020', 2, 'f'),
    (11,38,1,'grosse pietre (porfidi), sia a spigoli vivi, che arrotondati, alloggiati nelle negative dell''evidenza 5 (in giacitura primaria)', '16/02/2020', 2, 'f'),
    (11,39,1,'grosse pietre (porfidi), sia a spigoli vivi, che arrotondati, spostati dalla loro sede originaria (nelle negative dell''evidenza 5) e trasportate più a valle da US 32 (in giacitura secondaria)', '16/02/2020', 2, 'f'),
    (11, 40, 1, 'piccolo accumulo di piccole pietre, nell''evidenza 5, sul paleosuolo US 10. sono presenti molti ossi e qualche frammento ceramico', '16/02/2020', 2, 'f'),
    (11, 41, 1, 'lente carboniosa in copertura di us10, visibile in sezione2 (ftp5) documentata in piano con ftp9', '16/02/2020', 2, 'f'),
    (11, 42, 1, 'strato di pietroni e pietre in matrice sabbiosa, probabilmente accumulato naturalmente nel canale erosivo us -33', '16/02/2020', 2, 'f'),
    (11, 43, 2, 'canale erosivo ad est di evidenza 3. Tagliale us 17 e 18. riempito da us 42.', '16/02/2020', 2, 'f'),
    (11, 44, 1, 'riempimento in pietrine e sabbia e qualche coppo dentro il canale erosivo US -45', '16/02/2020', 2, 'f'),
    (11, 45, 2, 'piccolo canale erosivo', '16/02/2020', 2, 'f');
COMMIT;
