BEGIN;
INSERT INTO diario(data,descrizione,operatore,scavo) VALUES
('20/07/2020','Inizio dei lavori. Allestimento del cantiere. Il mezzo meccanico inizia i lavori di scavo in Pt.2 che vengono assisti. Documentazione delle massicciate sotto i pavimenti moderni e di un rimasuglio di pavimento cocciopesto (USS 9000-9006); si controlla il mezzo meccanico durante lo scavo nella stanza 2. si effettua una prima documentazione (solo fotografica) della situazione dei pavimenti più recenti. si compilano le prime schede US. nella stanza 1 si pulisce e si documenta fotograficamente uno schienamento di detriti (US 9008). nella stanza 2 si rimuove a mezzo meccanico vs 9005 ovvero un accumulo di detriti in matrice Franco argillosa Bruno scuro a riempimento di un taglio reale che ha demolito varie strutture. attualmente la situazione nella stanza due è la seguente: vs9000 uguale piano pavimentale in cemento moderno; vs 9001 risarcimento in Malta del pavimento in coccio pesto vs 9003 tagliato in superficie dalla negativa vs Nino 9002; vs 9003 e anche tagliato in maniera verticale da vs - 9004 una fossa di fondazione per il muro USM 9007 e le rispettive fondamenta vs 9006. USM 9007 non è stato osservato in cantiere ma è visibile in base alle negative lasciate sul perimetrali della stanza 2 e sul soffitto. USM 9007 è stato rimosso mezzo meccanico prima dell''inizio del controllo archeologico. nella stanza 2 è presente anche un pozzo che attualmente non ha ancora un numero di vs. ad oggi l''ipotesi è che una negativa areale piuttosto tarda forse bassomedievale abbia intaccato un pavimento bassomedievale e altre strutture tra cui forse un muro altomedievale. la negativa in questione avrebbe anche creato il piano di cantiere su cui sarebbero state sparse le macerie che vanno a costituire lo strato di ricarica vs 9005 ovvero la sotto preparazione del pavimento in cocciopesto vs 9003 che potrebbe anche essere un pavimento settecentesco.',4,45),

('21/07/2020','in mattinata Si posizionano con il GPS alcuni punti fissi con quota ortometrica nel cortile del monastero di Santa Maria in valle. con la stazione totale si lanciano altri tre punti fissi sulle pareti dei perimetrali della stanza due. da metà mattinata alla fine del pomeriggio si esegue la pulizia della situazione palinsesti ca attualmente visibile in stanza due. si recuperano anche le quote delle prime vs positive date il giorno precedente leggendo le in sezione.',4,45),

('22/07/2020','in mattinata si prosegue con la pulizia areale della stanza pt2. nella stanza pt1 si prosegue la rimozione controllata a mezzo meccanico dvs 9008. durante tale rimozione vengono alla luce due ipotetici vani sepolti. il primo di essi è confermato ed era riempito da un crollo asportato a mezzo meccanico vs9011. sempre in mattinata si comincia la pulizia nella stanza pt2.1. nel pomeriggio si concludono i lavori con l''escavatore nella stanza pt1; si termina la pulizia areale nella stanza pt2 e si documenta; si termina anche la pulizia nella stanza pt2.1 e si documenta.',4,45),

('23/07/2020','in pt1 si cominciano a svuotare i vani 1 e 3. il vano 3 è riempito da vs 9017 ovvero un accumulo di detriti in matrice Franco sabbiosa grigia sciolta punto al suo interno Si rinvengono anche frammenti di un pavimento in cemento moderno. a contatto con il fondo del vano 3 si trova vs9000 19 ovvero uno strato Franco limoso Bruno scuro. si documenta anche vs2019 e lo si rimuove. parallelamente si svuota anche il vano uno i suoi riempimenti sono simili a quelli del vano 3 e del vano 2 si esegue il controllo all''escavatore in pt3.',4,45),

('24/07/2020','si conclude la polizia di pt1 e nel pomeriggio La si documenta. come nelle altre stanze vi è una negativa reale vs 9020 riempita da un piano di cantiere vs 9023. si comincia il controllo al mezzo meccanico nella demolizione dei pavimenti di S1.l''escavatore comincia anche delle piccole demolizioni in pt4.',4,45),

('27/07/2020','si comincia la pulizia generale ppt3, nel quale si comincia lo svuotamento del vano 2 punto il vano 2 presenta riempimenti simili Al bano 1 e Albano 3. parallelamente si comincia la rimozione del livello di cantiere di ventesimo secolo in PT 2.1, ovvero vs 9013. in pt1 si comincia la pulizia della tomba 1 ovvero la tomba di un bambino all''altezza dell''entrata nella stanza.',4,45),

('28/07/2020','in mattinata si termina la pulizia dell nea situazione in PT 2.1 e si documenta. si comincia dunque la rimozione dell'' accumulo di detriti US 9033, sempre in pt2.1. sempre in mattinata si documentano e si rimuovono le tombe 1 e 2 in PT 1. sia la tomba uno che la tomba due sono fosse resti di fosse per inumazione di due bambini. si conservano gli scheletri i resti della Fossa e del riempimento è una piccola strutturazione in pietre in TB 1. ancora in mattinata si termina la pulizia in pt3 e si documenta. il pomeriggio si comincia la pulizia della situazione dopo lo scavo con l''escavatore in S1. nel frattempo, in pt 2. 1, si continua la rimozione di u.s. 9033 fino a completo esaurimento. verso la metà del pomeriggio si iniziano a scavare alcune uesse in pt3. Us 9049 viene scalata è documentata. si tratta del riempimento di una buca circolare di un diametro di circa 25 cm è di una profondità di circa 10 cm. il contenuto è carbonioso con la presenza di poche schegge di ossi di fauna. segue lo scavo di Us 9052, che riempie la struttura Us 9051. si tratta di un altro vano per la fognatura postmedievale. inizia anche lo scavo di Us 9053 che però non viene terminato. Stesso vale per Us 9016. il mezzo meccanico ha concluso lo scavo di Pt5, ed è avanzato con la demolizione del pavimento pt4.' ,4,45),

('29/07/2020','in PT 2.1 si rimuove vs 9035 (un accumulo di pietre e detriti in una matrice Franco sabbiosa sciolta con ceramica dall''epoca altomedievale a postmedievale). sempre in pt 2.1 si rimuove USM 9039 (una base di strutturina moderna a pianta quadrata). sì in insacchettano e si registrano tutti i reperti finora emersi e si incomincia il recupero degli RR. In Pt.3  inizia lo scavo dello strato numero 9054, dopo lo scavo e la documentazione e lo strato numero 9057. inoltre viene scavato e documentato il fondo Usm 9026. gli operatori del mezzo meccanico oggi sono assenti.',4,45),

('30/07/2020','nella stanza PT 2.1 si rimuove US 9036, uno strato particolarmente ricco di reperti all''interno del vano 4. sotto US 9036 si rinviene la negativa US -9063, che sembrerebbe essere la fossa di fondazione dell''attuale perimetrale Sud di PT 2.1. all''interno di US -9063, si trova uno strato franco-sabbioso marrone chiaro dalla consistenza sciolta. In Pt.3 si continua e si conclude lo scavo di Us 9054. In Pt.4 si assiste allo scavo con mezzo meccanico, nell''angolo settentrionale della stanza viene scoperto un altro vano postmedievale con funzione di fognatura. raggiungendo il livello di meno 50 cm iniziano strati argillosi con resti di concotto. la stanza viene attraversata da due tubi moderni che restano in situ. il mezzo meccanico continua con lo svuotamento della vasca *vano5* in S1. inclusa in un pezzo di muratura postmedievale viene recuperato un pezzo di base di colonna. aggiunto una profondità di meno 2 metri si decide di fermare i lavori di svuotamento per ragioni di sicurezza.',4,45),

('31/07/2020','la giornata inizia con la sistemazione dei reperti di stanza 2.1. In stanza 3 viene documentata la situazione raggiunta e pulita (Ftp12) assegnando le nuove Us. gli operai iniziano con la preparazione della zona di scala 2 e dei vani 6 e 7 svuotando la zona dai mobili depositati. si inizia la pulizia di stanza 4. a mezzogiorno viene conclusa la pulizia. segue la documentazione di stanza 4. instanza PT 2.1 si rimuove US 9062 e si comincia lo scavo di US 9037',4,45),

('03/08/2020','La giornata inizia con la documentazione delle Us 9086 e 9087 in stanza 7. Si tratta della pavimentazione moderna e la sottostante preparazione massicciata. L''impresa continua con la rimozione con mezzo meccanico di Us 9087 (S2, Pt.6,7) che continua per tutta la giornata. Gli archeologi continuano le operazioni di scavo nelle stanze 2.1 e 3 (Us9055, 9069). Documentazione in stanza 3 con fotopiano 14. In Pt 2.1 si rimuovono le US 9037 9038 e 9040. Gestione reperti, schedatura delle unità stratigrafiche.',4,45),

('04/08/2020','In stanza 3 i lavori riprendono con la documentazione dei reperti registrati trovati in superfice dell''Us 9088. In seguito Us 9088 viene scavata. Copre le Us 9066 e 9089 che potrebbero essere ugualiate. Le pietre di Us 9066 si estendono in direzione sud-est. Nell''angolo orientale dell''area di scavo sta uscendo un piano argilloso (Us9095). Si conclude con le foto archeologiche della nuova situazione e con la documentazione 3d. Intanto continuano i lavori di demolizione nelle stanze 6 e 7. Nell angolo settentrionale di stanza 7 si è trovato un altro vano sotterraneo che viene svuotato coll''aiuto del mezzo meccanico. in PT 2.1 si documentano Leu US 9092, 9093, 9094. nel pomeriggio si asporta US 9092 è parzialmente US 9093 e 9094.',4,45),

('05/08/2020','si riprendono gli scavi nelle stanz mae 2.1 e 3 con la documentazione dei livelli raggiunti il giorno prima e con la gestione dei reperti. in stanza 7 il mezzo meccanico inizia lo scavo di Us 9103 e raggiunge la quota di meno 50 cm a metà mattinata. vista l''omogeneità dello strato si decide di abbassarsi ulteriormente col mezzo meccanico. nell''area settentrionale della stanza è stata messa in luce una struttura sotterranea rettangolare intonacata all''interno che dovrebbe datare in epoca molto recente è stata svuotata Con l''aiuto del mezzo meccanico. Nell''area nordest della stanza stanno uscendo i resti di un muro in pietre e malta. scavo di ulteriori 15cm in stanza 7 coll''aiuto del mezzo meccanico. Dopo pranzo approfondimento lungo il muro che emerge nel settore settentrionale della stanza. Livelli di sabbia e ghiaia che sembrano di essere di origine naturale. In stanza 6 si scava a mezzo meccanico ed assistenza archeologica uno strato di macerie prevalentemente composto da pietre, laterizi e calce che si basa su una superficie orizzontale di calce ancora non ben definita. Per il momento ci si ferma a questo livello. É emerso un''ulteriore vano sotterraneo ai piedi della scala S2. Segue la documentazione di area 7000 per localizzare l''andamento delle mura verso Pt.7. Finalmente si inizia lo scavo di Us 9066 in Pt.3 e si documenta Ftp  18 in Pt. 2.1, che registra la situazione dopo la rimozione di US 9092, 9094 e e dopo lo svuotamento US -9105 e -9107.',4,45),

('06/08/2020','In stanza PT 2.1 si rimuove US 9100 e 9101 e si documenta. Si procede dunque alla rimozione dello strato di incendio US 9109 e del butto US 9102, cominciando anche la rimozione di US 9104. Si decide, inoltre, di codificare con un nuovo numnero la porzione di US 9093 nei pressi dell''entrata della stanza (uno strato a forma di *L* in pianta), correggendo gli appunti nel gruppo WA con il nuovo numero US )112. In Pt.3 si continua lo scavo di Us9066. In area 7000 si conclude la documentazione delle mura della città per chiarire l''andamento verso Pt.7. In mattinata gli operai hanno sitemato i loro macchinari e materiali fino ca. le ore 10',4,45),

('07/08/2020','In stanza 3 continua lo scavo di Us 9066. Ritrovamento di ulteriori ossi e ceramica altomedievale e tardoantica. Rendicontazione dei volumi finora scavati con dottoressa Borzacconi.',4,45),

('10/08/2020','Si inizia la pulizia in stanza 7. In stanza 3 continua e viene compiuto lo scavo di Us 9066. Si documenta Us9095 con Ftp 22. Iniziata e compiuta la pulizia finale di Us 9066. Individuati nuovi strati con i numeri 9115, 9116, e le buche circolari 9118 e 9120. Documentazione della nuova situazione con fotopiano 23. Continua la gestione dei reperti con lavaggio, catalogazione e sistemazione nell''ufficio di scavo. In PT 2.1 si rimuovono le US 9113, 9114 e, parzialmente, 9112 e 9123.',4,45),

('11/08/2020','In stanza 3 si inizia lo scavo di US9116. In diminuzione la quantità dei materiali, ma si presenta sempre tra l''altomedioevo ed il tardoantico. Terminato lo scavo di US9116 troviamo esposto US 9115 su tutta l''area di scavo. Possibile individuare varie buche (Us-9128, -9131, -9133). documentazione della situazione con fotopiano 27. Sono terminati i lavori di pulizia in stanza 7 ed hanno iniziato in stanza 6. in PT 2.1 si rimuove US 9121, all''interno del vano quattro, documentando quindi in quest''area la situazione finale. all''esterno del vano 4 si rimuove US 9127, procedendo dunque ad una documentazione generale.',4,45),

('12/08/2020','Inizia lo scavo di US 9115 che si estende su tutta l''area di stanza 3. Al lato nord-ovest si presenta con una profondità di ca. 25cm che diminuisce verso sud-est a ca. 10cm. In tardo pomeriggio
l''operazione di scavo è terminata e la nuova situazione (esposta Us9142 con varie buche) viene documentata con Ftp 29. Continuano i lavori di pulizia che si concentrano su Pt.6. in PT 2.1 si scava US 9124, mettendo in luce un antico focolare. si documenta quindi la nuova situazione e si ricomincia a scavare togliendo US 9137, ovvero un accumulo di cronico di ceneri. si prepara e si pulisce dunque tutta l''area per la nuova documentazione.',4,45),

('13/08/2020','In stanza 3 si inizia lo scavo dei tagli Uss -9154, -9155, -9158 che vengono documentate con il fotopiano 31. Segue so scavo di US 9142, un livello argilloso di colore marrone-rossiccio con presenza di ghiaia centimetrica e pluricentimetrica. Scavando si mettono in luce vari nuovi tagli a forma circolare (USS -9150 - 9163). Esce un piano prevalentemente argilloso (Us 9164) che viene liberato e documentato con fotopiano 32. Iniziano i lavori di pulizia in stanza 5 che a fine giornata sono già in fase finale. La situazione viene documentata con fotopiano 34.',4,45),

('14/08/2020','In stanza 3 con fotopiano33 si documentano vari tagli circolari (9156, 9158, 9165, 9167) alineati e si scava un approfondimento che sotto US6164 mette in luce strati geologici. In accordo con la direzione dei lavori si decide di sosperndere i lavori in questa stanza per il momento. Intanto alla situazione iniziale in stanza 5 vengono asegnate le US 9171, 9172, 9173 e documentate con fotopiano 34. In stanza 7 vengono assegnate le numerose Us e seguono le foto archeologiche e la documentazione tridimensionale con fotopiano 35.  Fotopiano 36 copre l''area di stanza 6 e di scala 2. Intanto continuano i lavori di pulizia sotto scala 1.',4,45),

('17/08/2020','In mattinata continuano i lavori di pulizia sotto scala 1 e contemporaneamente l''assegnazione dei numeri di Us in stanza 6 e sotto scala 2. Seguono le foto archeologiche di queste due aree. I lavori continuano con lo scavo dell''individuo Us 9222 e la sua documentazione (tomba 3/20) in S2 con i fotopiani 37 e 38. In stanza 7 vengono svuotati e campionati i tagli -9181, -9185, -9187. In S2 segue lo scavo di Us 9219. In S1 la giornata si conclude con la documentazione 3d della situazione complessiva con ftp39.',4,45),

('18/08/2020','In S2 la giornata inizia con la documentazione di Us -9218 e con la sistemazione dei reperti rinvenuti nel corso dello scavo di Us9219. In S1 si assegnano i numeri delle nuove unità stratigrafiche seguito dalle foto archeologiche di fotopiano 39. In S2 riprendono le attività di scavo con Us9220. In stanza 7 inizia l''indagine tra le Us 9182 e 9184 a ridosso delle mura. La nuova situazione viene documentata con fotopiano 41. In Pt.1, in accordo con la direzione dei lavori é stato smontato la metà del muro meridionale di Usm9024 per ricavare la sezione della stratigrafia dell''area. La situazione viene documentata con fotopiano 40. Riprendono i lavori anche in Pt.6: Scavo delle Us 9200, 9207 e 9208. Messa in luce delle Us 9199 e 9209 nel vano centrale di Pt.6. Documentati con Ftp42.',4,45),

('19/08/2020','Si riprendono le attività di scavo nelle stanze S2 e Pt.6. Dopo la documentazione del giorno prima si scava US 9209 nel vano quadrato nell''area centrale di Pt.6 e Us 9204 nell''area settentrionale di Pt.6. Nell''ultima sembra che si riesca a intaccare le cinta murarie su una lunghezza di ca. 1 metro. Us 9209 sembra di essere un piano finalizzato alla livellazione dello strato sottostante Us 9238 che è formato prevalentemente da pietroni di dimensioni pliuridecimetriche. Viene messo in luce Us 9238 e documentata la nuova situazione con fotopiano 43. Dopo di questo si inizia lo scavo dell'' Us che non si conclude a fine giornata. Sembra che si tratti di un''altro vano per le fognature del monastero.',4,45);

COMMIT;
